name: 'Jenkins Action'
description: 'Trigger job on Jenkins'
author: 'Comtravo GmbH'
inputs:
  baseUrl:
    required: true
    description: 'Jenkins URL ex: https://username:password@ci.foo.com'
  jobUrl:
    required: true
    description: 'Jenkins job url to trigger'
  jobParams:
    description: 'Jenkins job params'
    default: '{}'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
